name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_persian_calendar:
    path: ../
  shamsi_date: ^1.0.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Bold.ttf
        - asset: assets/fonts/Vazirmatn-Medium.ttf
        - asset: assets/fonts/Vazirmatn-Regular.ttf
